# Google Drive Configuration Example
# Copy this to gdrive_config.toml and update with your settings

[google_drive]
# Google Drive folder ID containing your .h5 files
# Get this from the URL when viewing your folder in Google Drive
# https://drive.google.com/drive/folders/YOUR_FOLDER_ID_HERE
folder_id = "your_google_drive_folder_id_here"

# Path to your Google OAuth2 credentials JSON file
# Download from Google Cloud Console and place in project root
credentials_file = "credentials.json"

# Local cache directory for downloaded files
cache_dir = "./gdrive_cache"

# Mapping of logical names to Google Drive file IDs
# This allows you to refer to files by meaningful names instead of IDs
[google_drive.file_mappings]
# Format: logical_name = "google_drive_file_id"
nass_data = "1ABC123_your_nass_data_file_id_here"
esr_data = "1XYZ789_your_esr_data_file_id_here"  
market_data = "1DEF456_your_market_data_file_id_here"
agricultural_data = "1GHI789_your_agricultural_data_file_id_here"

# Example mappings for different databases
[table_clients]
# Map database names to Google Drive file identifiers
[table_clients.nass_db]
gdrive_file = "nass_data"  # References the logical name above

[table_clients.esr_db]
gdrive_file = "esr_data"

[table_clients.market_db]
gdrive_file = "market_data"

# Cache settings
[cache_settings]
# Automatically clear cache files older than this many days (0 = never)
auto_clear_days = 7

# Maximum cache size in MB (0 = unlimited)
max_cache_size_mb = 1000

# Check for file updates every N hours
update_check_hours = 24