
[NG]
market_ticker = 'NG_F'
cot_name = 'NATURAL_GAS'

[CL]
market_ticker = 'CL_F'
cot_name = "CRUDE_OIL"

[RB]
market_ticker = 'RB_F'
cot_name = "RBOB_GASOLINE"

[LE]
market_ticker = 'LE_F'
cot_name = 'LIVE_CATTLE'

[GF]
market_ticker = 'GF_F'
cot_name = "FEEDER_CATTLE"

[HE]
market_ticker = 'HE_F'
cot_name = "LEAN_HOGS"