[product_types]
PET = 'petroleum'

[PET.sum]
supply_summary = 'sum/sndw'

[facets.products]
crude_oil = 'EPC0'
distillate = 'EPD0'
gasoline = 'EPM0C'
natural_gas = 'EPG0'

[facets.duoareas]
USA = 'NUS'


[futs]
crude_oil = "RCLC"
gasoline = "EER_EPMRR_PE4_Y35NY_DPG"






